server:
  port: 8080
spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/testdb
    username: postgres
    password: postgres
    platform: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: nghiemducnam0312@gmail.com
    password: sdxm fmia vuzf bvmq
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

namnd:
  app:
    jwtSecret: bezKoderSecretKey
    jwtExpiration: 900000
    jwtRefreshExpiration: 604800000
    passwordResetBaseUrl: ${PASSWORD_RESET_BASE_URL:http://localhost:3000/reset-password}

logging:
  level:
    root: info
    com.namnd.springjwt: debug
    org:
      springframework:
        jdbc:
          core:
            JdbcTemplate: DEBUG
            StatementCreatorUtils: TRACE
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
